"use client";

import { motion } from "framer-motion";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { Shield, Lock, Hash, CheckCircle2 } from "lucide-react";

const fadeInUp = {
  hidden: { opacity: 0, y: 20 },
  visible: { opacity: 1, y: 0, transition: { duration: 0.6 } },
};

export default function FairPlayPage() {
  return (
    <motion.div
      initial="hidden"
      animate="visible"
      className="min-h-screen bg-background p-6"
    >
      <div className="max-w-7xl mx-auto space-y-8">
        <motion.div variants={fadeInUp} className="text-center space-y-4">
          <h1 className="text-4xl font-bold flex items-center justify-center gap-2">
            <Shield className="w-10 h-10" />
            Fair Play Policy
          </h1>
          <p className="text-xl text-muted-foreground max-w-2xl mx-auto">
            Learn how we ensure fair and transparent gaming for all players
          </p>
        </motion.div>

        <motion.div variants={fadeInUp}>
          <Card>
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <Hash className="w-6 h-6" />
                Provably Fair System
              </CardTitle>
              <CardDescription>
                Understanding how our games ensure randomness and fairness
              </CardDescription>
            </CardHeader>
            <CardContent className="space-y-6">
              <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
                {["Server Seed", "Client Seed", "Verification"].map(
                  (title, index) => (
                    <motion.div
                      key={index}
                      variants={fadeInUp}
                      className="space-y-2"
                    >
                      <div className="w-10 h-10 rounded-full bg-primary/10 flex items-center justify-center">
                        <span className="text-xl font-bold">{index + 1}</span>
                      </div>
                      <h3 className="font-medium">{title}</h3>
                      <p className="text-sm text-muted-foreground">
                        {title === "Server Seed" &&
                          "A random seed is generated by our server for each game round"}
                        {title === "Client Seed" &&
                          "Players can provide their own seed to influence the outcome"}
                        {title === "Verification" &&
                          "Results can be verified using our open-source algorithm"}
                      </p>
                    </motion.div>
                  )
                )}
              </div>
            </CardContent>
          </Card>
        </motion.div>

        <motion.div
          variants={fadeInUp}
          className="grid grid-cols-1 md:grid-cols-2 gap-6"
        >
          {["Aviator Game", "Color Game"].map((game, index) => (
            <motion.div key={index} variants={fadeInUp}>
              <Card>
                <CardHeader>
                  <CardTitle>{game}</CardTitle>
                  <CardDescription>
                    {game === "Aviator Game"
                      ? "How fairness is ensured in Aviator"
                      : "Fair play mechanics in Color Game"}
                  </CardDescription>
                </CardHeader>
                <CardContent className="space-y-4">
                  {[
                    "Random Multiplier",
                    "Instant Verification",
                    "Transparent Odds",
                  ].map((feature, idx) => (
                    <motion.div
                      key={idx}
                      variants={fadeInUp}
                      className="flex items-start gap-4"
                    >
                      <CheckCircle2 className="w-5 h-5 text-green-500 mt-1" />
                      <div>
                        <h4 className="font-medium">{feature}</h4>
                        <p className="text-sm text-muted-foreground">
                          {feature === "Random Multiplier" &&
                            "Each game's multiplier is determined by a cryptographic hash function"}
                          {feature === "Instant Verification" &&
                            "Players can verify each round's fairness immediately after completion"}
                          {feature === "Transparent Odds" &&
                            "House edge and winning probabilities are clearly displayed"}
                        </p>
                      </div>
                    </motion.div>
                  ))}
                </CardContent>
              </Card>
            </motion.div>
          ))}
        </motion.div>

        <motion.div variants={fadeInUp}>
          <Card>
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <Lock className="w-6 h-6" />
                Security Measures
              </CardTitle>
              <CardDescription>
                Additional steps we take to ensure fair play
              </CardDescription>
            </CardHeader>
            <CardContent>
              <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                {["Anti-Cheating Systems", "Player Protection"].map(
                  (section, index) => (
                    <motion.div
                      key={index}
                      variants={fadeInUp}
                      className="space-y-4"
                    >
                      <h3 className="font-medium">{section}</h3>
                      <ul className="space-y-2 text-sm text-muted-foreground">
                        {section === "Anti-Cheating Systems" &&
                          [
                            "Multiple account detection",
                            "Bot prevention measures",
                            "Regular security audits",
                          ].map((item, idx) => (
                            <li key={idx} className="flex items-center gap-2">
                              <CheckCircle2 className="w-4 h-4 text-green-500" />
                              {item}
                            </li>
                          ))}
                        {section === "Player Protection" &&
                          [
                            "Responsible gaming limits",
                            "Self-exclusion options",
                            "Transparent transaction history",
                          ].map((item, idx) => (
                            <li key={idx} className="flex items-center gap-2">
                              <CheckCircle2 className="w-4 h-4 text-green-500" />
                              {item}
                            </li>
                          ))}
                      </ul>
                    </motion.div>
                  )
                )}
              </div>
            </CardContent>
          </Card>
        </motion.div>
      </div>
    </motion.div>
  );
}
